/* token.h - token kinds produced by the lexer. */
#ifndef BROKM_TOKEN_H
#define BROKM_TOKEN_H

typedef enum {
  /* punctuation */
  TOKEN_LPAREN, TOKEN_RPAREN, TOKEN_LBRACE, TOKEN_RBRACE,
  TOKEN_LBRACKET, TOKEN_RBRACKET,
  TOKEN_COMMA, TOKEN_SEMICOLON, TOKEN_COLON,

  /* arithmetic / assignment */
  TOKEN_PLUS, TOKEN_MINUS, TOKEN_STAR, TOKEN_SLASH, TOKEN_PERCENT,
  TOKEN_PLUS_PLUS, TOKEN_MINUS_MINUS,
  TOKEN_EQ,
  TOKEN_PLUS_EQ, TOKEN_MINUS_EQ, TOKEN_STAR_EQ, TOKEN_SLASH_EQ, TOKEN_PERCENT_EQ,
  TOKEN_AMP_EQ, TOKEN_PIPE_EQ, TOKEN_CARET_EQ, TOKEN_SHL_EQ, TOKEN_SHR_EQ,

  /* comparison / logical */
  TOKEN_EQ_EQ, TOKEN_BANG, TOKEN_BANG_EQ,
  TOKEN_LESS, TOKEN_LESS_EQ, TOKEN_GREATER, TOKEN_GREATER_EQ,

  /* bitwise / shift */
  TOKEN_AMP, TOKEN_AMP_AMP, TOKEN_PIPE, TOKEN_PIPE_PIPE,
  TOKEN_CARET, TOKEN_TILDE, TOKEN_SHL, TOKEN_SHR,

  /* literals */
  TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_INT, TOKEN_FLOAT,

  /* keywords */
  TOKEN_TYPE, /* U0 U8 U16 U32 U64 I8 I16 I32 I64 F64 Bool */
  TOKEN_IF, TOKEN_ELSE, TOKEN_WHILE, TOKEN_FOR, TOKEN_DO, TOKEN_RETURN,
  TOKEN_SWITCH, TOKEN_CASE, TOKEN_DEFAULT, TOKEN_BREAK, TOKEN_CONTINUE,
  TOKEN_TRUE, TOKEN_FALSE, TOKEN_NIL,

  TOKEN_ERROR, TOKEN_EOF
} TokenType;

typedef struct {
  TokenType type;
  const char *start;
  int length;
  int line;
} Token;

#endif /* BROKM_TOKEN_H */
